platform: linux

inputs:
- name: git-pr

run:
  path: entrypoint.sh
  args:
    - bash
    - -excu
    - |
      cd git-pr

      # Disable logging of commands that contain secrets.
      set +x
      echo "Logging in to Docker using Vault secrets"
      docker login -u="((quayio.username))" -p="((quayio.password))" quay.io
      set -x

      # Run the main body of the build
      ./ci/scripts/build.sh
